import os

env = Environment(CC='i686-elf-gcc',
	AS='i686-elf-as',
	
	CCFLAGS = '-ffreestanding -std=gnu99 -O2 -Wall -Wextra',
	CPPPATH=['.', 'lib'],
	ENV = {'PATH' : os.environ['PATH']})


source = Split("""
core.c
memory.c
terminal.c
util/mini-printf.c
lib/string.c
boot.asm
""")

object = env.Object(source = source)
core = env.Program(target = 'p11-core', LINKFLAGS = '-T linker.ld -nostdlib -ffreestanding -O2 -Wall -Wextra', source = object)

